Signup/Signin API
wecode-bootcamp-korea/10-tenverse-backend pull request #1
Opened 2020-07-20 08:30 UTC by soojung601

2020-07-20 08:44 UTC, soheon-lee commented on converse/urls.py
>  """
파일 내부 사용하지 않는 안내 코드들은 모두 제거해주세요

2020-07-20 08:44 UTC, soheon-lee commented on user/models.py
> +    phone_number = models.IntegerField()
전화번호를 정수 필드로 입력할 시 '010'이 처리되지 않으며, 통상 CharField로 처리합니다.

2020-07-20 08:44 UTC, soheon-lee commented on user/views.py
> +            if ('@' in data['email']) and (data['password']>=8):
- 이메일 형식엔 `@`과 더불어 `.`도 필수 입력 값입니다.
- 컨버스 웹에서 비밀번호 형식을 다시 확인하여 정규식을 이용한 validation 절차를 거쳐주세요.

2020-07-20 08:44 UTC, soheon-lee commented on user/views.py
> +                   access_token =  jwt.encode({'user_id' : user.id}, SECRET_KEY, algorithm = 'HS256')
토큰을 암호화하는 알고리즘이 외부에 노출되었습니다. `SECRET_KEY`와 마찬가지로 `ALGORITHM`또한 git에 업로드하지 않는 외부 숨김 파일에 분리해주세요.

2020-07-21 01:33 UTC, soheon-lee commented on user/models.py
> +    email       = models.EmailField(max_length = 254)
- 이메일 계정은 사용자를 구별하는 기능을 하므로 데이터베이스 단계에서부터 중복되지 않도록 `unique = True` 설정하는 것이 좋습니다.
- `max_length`는 255로 변경하는 것을 추천드립니다.

2020-07-21 01:33 UTC, soheon-lee commented on user/models.py
> +    phone_number = models.CharField(max_length = 50)
- 핸드폰 번호는 이메일 계정과 마찬가지로 사용자마다 다른 값을 지정해주도록 사전에 설정해두는 것을 추천드립니다. `unique`한 속성으로 지정해주세요.

2020-07-21 01:33 UTC, soheon-lee commented on user/views.py
> +                if re.search(re.compile("^(?=.*[a-zA-Z])(?=.*\d)(?=.*[!@#$%&*])[a-zA-Z\d!@#$%&*]{8,}$"), data['password']):
로직의 순서에 조금 더 집중해주세요 🙂
이메일과 비밀번호의 유효성을 먼저 검사한 후, valid한 데이터라면 그 때 이메일 중복 여부를 평가하는 것이 보다 효율적입니다.

현재 순서로 진행하실 경우, 이메일의 유효성이 맞지 않을 때에도 filter( ).exists( )를 평가하는 `if` 로직을 거쳐야합니다. 필요하지 않은 평가는 수행하지 않아도 됩니다 :)

2020-07-21 01:33 UTC, soheon-lee commented on user/views.py
> +                   return JsonResponse({'access_token' : access_token.decode('utf-8')}, status = 200)
비밀번호 틀렸을 때의 예외처리가 되어있지 않습니다. 확인해주세요~

2020-07-21 06:54 UTC, soheon-lee commented on user/views.py
> +        try:
로그인 진행할 때에도 이메일과 비밀번호 validation 진행해주세요 :)

2020-07-21 06:54 UTC, soheon-lee commented on user/models.py
> +        db_table = 'users'
`UserDetail`로 따로 분리하지 않으시고 `User`에서 모두 관리하셔도 괜찮습니다 :)

2020-07-21 06:54 UTC, soheon-lee commented on user/views.py
> +                    ).save()
`User`테이블 하나로 통합된다면 view로직도 간소화 하시는걸 추천드립니다.

2020-07-22 02:31 UTC, evergreen-david requested changes

2020-07-22 02:31 UTC, evergreen-david commented on user/views.py
> +            if not validation(data['email'], data['password']):
로그인할때는 실제로 잘못된 값을 입력해도 입력은 되고 비밀번호가 틀렸다고 알려주기 때문에 validation 하지 않고 bcrypt checkpw 로 비교한 후에 인증실패를 리턴해야 할 것 같습니다.

2020-07-22 07:36 UTC, evergreen-david requested changes

2020-07-22 07:36 UTC, evergreen-david commented on user/tests.py
> +client = Client()
클래스 변수로 수정 부탁 드립니다.

2020-07-22 07:45 UTC, evergreen-david requested changes

2020-07-22 07:45 UTC, evergreen-david commented on user/tests.py
> +from django.test import (
임포트 순서 확인 부탁 드려요.

2020-07-23 07:20 UTC, evergreen-david approved these changes

2020-07-23 07:21 UTC, merged

2020-07-23 07:21 UTC, evergreen-david commented
LGTM 👍