장바구니 API
wecode-bootcamp-korea/10-tenverse-backend pull request #10
Opened 2020-07-28 07:05 UTC by soojung601

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요. 예: 로그인 엔드포인트 구현)       
	장바구니 모델링
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)
- 장바구니 모델링

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-07-28 08:51 UTC, evergreen-david requested changes

2020-07-28 08:51 UTC, evergreen-david commented on order/views.py
> +        user = User.objects.get(id=user_id)
코드다 올린것 맞는지 확인 부탁 드립니다. Return 이 보이지 않네요.

2020-07-29 05:17 UTC, evergreen-david requested changes

2020-07-29 05:17 UTC, evergreen-david commented on order/views.py
> +                product.save()
except 는 말그대로 예외를 처리하는 코드가 들어가야 합니다.
try 구문 안에서 상품있는지 없는지 exists 로 확인해서 해당코드를 구현 부탁 드립니다.

2020-07-29 05:17 UTC, evergreen-david commented on order/views.py
> +        try:
except KeyError 가 누락 되어있습니다. 확인 부탁 드립니다.

2020-07-30 08:52 UTC, soheon-lee commented
LGTM

2020-07-30 08:52 UTC, merged