Mainpage View
wecode-bootcamp-korea/10-tenverse-backend pull request #4
Opened 2020-07-24 13:59 UTC by soojung601

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요. 예: 로그인 엔드포인트 구현)       
		 Mainpage View 추가
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)
- mainpage view 추가

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-07-27 02:08 UTC, evergreen-david requested changes

2020-07-27 02:08 UTC, evergreen-david commented on product/models.py
> +    is_hover   = models.BooleanField(default = False)
```suggestion
    is_ hovered   = models.BooleanField(default = False)
```

2020-07-27 02:14 UTC, evergreen-david requested changes

2020-07-27 02:14 UTC, evergreen-david commented on product/views.py
> +            'subimage__is_hover'    : 'True'
True를 왜 문자열로 처리하는지 설명 부탁 드립니다. True 로 해도 되지않을까요 ?

2020-07-27 02:14 UTC, evergreen-david commented on product/views.py
> +        shoes.append({'page_three' : list(shoe.filter(**{
리스트 컴프리헨션으로 처리 부탁 드립니다.

2020-07-27 02:14 UTC, evergreen-david commented on product/views.py
> +        shoes.append({'page_three' : list(shoe.filter(**{
그리고 page_one, two, three 보다는 필요한 요소만 fetch 해가도록 API 구성하는게 좋아 보입니다.
예를들어, page_one, two, three 요소가 전부 상품에 대한것이고 쿼리스트링이나 파라미터로 구분해서 줄수 있으면 엔드포인트 하나로 묶어도될것같아요!

2020-07-27 04:47 UTC, soojung601 commented on product/views.py
> +            'subimage__is_hover'    : 'True'
그러게요...... 수정했습니다......

2020-07-27 04:48 UTC, soojung601 commented on product/views.py
> +        shoes.append({'page_three' : list(shoe.filter(**{
프론트에서 메인페이지가 한페이지로 되어있어서...! 이렇게 달라고 요청했어요..!
그리고 리스트 컴프리헨션 하려다 프론트랑 데이터 형식을 바꿔서 딕셔너리로 전달해주기로 했습니다..!

2020-07-27 08:00 UTC, soheon-lee commented on product/views.py
> +        }))
shoes 딕셔너리를 선언한 27번줄과 로직이 분리되어 있어 가독성이 떨어집니다.
특별한 이유가 없다면 빈 딕셔너리 선언을 하고 키-밸류를 추가하기보다는, `womens_collection`, `jack_prcell`등의 키를 가진 딕셔너리 `shoes`를 바로 할당하는 것이 어떨까요?

2020-07-28 05:33 UTC, soheon-lee commented on product/models.py
>      price               = models.IntegerField()
`price` Decimal field 이고 , 통상적으로 소수점 둘째자리 혹은 넷째자리까지 허용합니다.

2020-07-28 05:33 UTC, soheon-lee commented on product/views.py
> +            'womens_collection' : list(shoe.filter(shoe__detail__name__contains = '척테일러')),
```suggestion
            'women_collection' : list(shoe.filter(shoe__detail__name__contains = '척테일러')),
```

2020-07-28 05:33 UTC, soheon-lee commented on product/views.py
>              shoe_list[i]['color_list'] = list(Color.objects.filter(**{
```suggestion
        for shoe in shoe_list:
            shoe['color_list'] = list(Color.objects.filter(**{
```

for 문에서 index `i`가 꼭 필요한 경우가 아니라면 리스트를 바로 순회하여도 됩니다.
변수 이름은 가독성을 위하여 `i`가 아닌 단어로 대체해주세요

2020-07-28 05:33 UTC, soheon-lee commented on product/views.py
> +                'shoecolor__shoe__id'               : shoe_list[i]['product_detail']['shoe__id'],
```suggestion
                'shoecolor__shoe__id'               : shoe['product_detail']['shoe__id'],
```

2020-07-28 08:31 UTC, evergreen-david approved these changes

2020-07-28 08:31 UTC, merged