상품 detail API
wecode-bootcamp-korea/10-tenverse-backend pull request #5
Opened 2020-07-25 07:32 UTC by soojung601

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요. 예: 로그인 엔드포인트 구현)       
		 상품 detail API 구현
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)
- url 추가
- views 추가

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-07-27 02:01 UTC, evergreen-david requested changes

2020-07-27 02:01 UTC, evergreen-david commented on product/views.py
> +                shoe__id = list(product.values('shoe__id'))[0]['shoe__id']
```suggestion
                shoe__id = list(product.values('shoe__id')).first()['shoe__id']
```

2020-07-27 08:47 UTC, evergreen-david commented
unit test 안돌아가지 않나요 ? subImage 에 is_hover 없는것같아요

2020-07-28 08:46 UTC, evergreen-david requested changes

2020-07-28 08:46 UTC, evergreen-david commented on product/tests.py
> +            "price": 95000,
model decimal 인데 정수와 다르지않을까요 ?

2020-07-29 05:20 UTC, evergreen-david requested changes

2020-07-29 05:20 UTC, evergreen-david commented on product/views.py
> +                price         = F('shoe__price'),
F저장하면 Decimal 이 String화 되어서 유닛테스트 실패하지 않나요 ? 
그리고 프론트에 리턴보낼때 숫자가 아닌 String으로 전달될것같은데 이부분 확인 부탁 드립니다.

2020-07-29 05:23 UTC, evergreen-david requested changes

2020-07-29 05:23 UTC, evergreen-david commented on product/views.py
> +                price         = F('shoe__price'),
그리고 여기도 동일한 커멘트 드립니다.
https://github.com/wecode-bootcamp-korea/10-tenverse-backend/pull/8#discussion_r461426313

2020-07-30 06:41 UTC, soheon-lee commented
LGTM

2020-07-30 06:41 UTC, merged