Product/filter API
wecode-bootcamp-korea/10-tenverse-backend pull request #8
Opened 2020-07-27 14:12 UTC by soojung601

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요. 예: 로그인 엔드포인트 구현)       
 product/filter API
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요)
- product/filter 엔드포인트 구현

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-07-28 05:37 UTC, soheon-lee commented on product/views.py
> +        ).values('id','shoe__id', 'name', 'price', 'main_image', 'sub_image')[int(page)*20:((int(page)+1)*20)-1]
한 페이지에 몇 개씩 받을지에 대한 숫자도 `20`으로 하드코딩 하기보다는, 프론트에서 받아오되 default로 20을 주는 것을 추천합니다.

2020-07-28 08:57 UTC, evergreen-david requested changes

2020-07-28 08:57 UTC, evergreen-david commented on product/views.py
> +        shoe_values = list(shoes.annotate(
ShoeColor.objects.filter 필터한이후에 관계된 객체들을 prefetch 또는 select related를 사용해서 가져와도 되지않을까요 ? annotate values 패턴이 동일하게 반복되는것같아 말씀 드립니다.

2020-07-28 11:07 UTC, soojung601 commented on product/views.py
> +        shoe_values = list(shoes.annotate(
prefetch나 select related 를 쓰면 코드가 너무 길어지고.. 필요하지 않은 정보도 select 해와서 매력이 없어요.....

2020-07-29 05:05 UTC, evergreen-david requested changes

2020-07-29 05:05 UTC, evergreen-david commented on product/views.py
> +        shoe_values = list(shoes.annotate(
우선 annotate 는 Count, Sum, Avg 한 결과값을 말그대로 annotate 할 때 사용합니다. 아래 공식문서 참고 부탁 드립니다.
https://docs.djangoproject.com/en/3.0/topics/db/aggregation/#generating-aggregates-for-each-item-in-a-queryset
그리고 필드에 있는데 그값을 다시 annotate 하면 불필요하게 메모리가 낭비 됩니다.
따라서 본 View에 사용하신 annote 는 일단 정리해 주시고, 다음과같이 개선 부탁 드리겠습니다.
가독성면에서도 좋다고 할 수 있습니다.

2020-07-29 05:05 UTC, evergreen-david commented on product/views.py
> +        }
아래는 제가 테스트 해본 코드인데 각필터값을 first 부분만 여러개 가져오도록 수정해서 테스트 부탁 드립니다.
```suggestion
            'gender_filters' : shoes.first().shoe.gender_segmentation.name
            'color_filters' : shoes.first().shoe.color.first().color_category.name
            'type_filters' : shoes.first().shoe.type_filter.name
            'size_filters' : shoes.first().size.first().name
```

2020-07-29 05:05 UTC, evergreen-david commented on product/views.py
> +            ).values('shoe_id', 'color_filter', 'main_image', 'sub_image'))
코드 라인도 훨씬 줄뿐더러 위에서 prefetch 또는 select_related 로 쿼리하시면 쿼리수 도 줄어 듭니다.
이부분 그때 알려드린 쿼리수와 실행시간 성능측정 데코레이터사용하셔서 확인해보시길 권장 드립니다.
```suggestion
                shoe_list = [{
            'product_detail' : {
                'id' : shoe.id,
                'name' : shoe.shoe.detail.name,
                'price' : shoe.shoe.price
            }
        } for shoe in shoes]

2020-07-29 12:22 UTC, soojung601 commented on product/views.py
> +            ).values('shoe_id', 'color_filter', 'main_image', 'sub_image'))
annotate는 사용하지 않았는데, list comprehension으로 for loop 두개를 합치고 싶었으나, 이미 생성된 객체의 value를 사용해야 하는부분이 있어서 합쳐지질 않아요...!

2020-07-30 08:35 UTC, soheon-lee commented on product/views.py
> +            if namefilter != None:
```suggestion
            if namefilter:
```

2020-07-30 08:35 UTC, soheon-lee commented on product/views.py
> +            if namefilter != None:
```suggestion
            if namefilter:
```

2020-07-30 08:38 UTC, soheon-lee commented
LGTM

2020-07-30 08:38 UTC, merged